arch: amd64
os: linux
dist: bionic
language: groovy
jdk:
- openjdk8
branches:
  only:
  - master
  - dev
  - /^feature\/.*$/
  - /^hotfix\/.*$/
node_js:
  - 12
addons:
  chrome: stable
  hosts: devt.ala.org.au

services:
  - elasticsearch
  - mongodb

before_install:
  - export TZ=Australia/Canberra
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo sh -c 'echo ES_JAVA_OPTS=\"-Xmx256m -Xms256m\" >> /etc/default/elasticsearch'
  - sudo service elasticsearch restart
  - sudo mkdir -p /data/fieldcapture/cache
  - sudo chmod o+xw /data
  - sudo chmod o+xw /data/fieldcapture
  - sudo chmod o+xw /data/fieldcapture/cache

# This is to prevent an unnecessary gradlew assemble by travis, as the asset compile is very slow and we have to
# clean before publishing (and hence assemble will happen a second time) to remove the clover instrumentation from the compiled classes.
install:
  - true

before_script:
- nvm install 12.14.1
- nvm use 12.14.1
- node -v
- npm install


cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew -PenableClover=true cloverGenerateReport --no-daemon
  - ./gradlew clientClean && ./gradlew clientInstall
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
  #- ./src/main/scripts/runFunctionalTests.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_wait 30 ./gradlew publish'

env:
  global:
  - secure: cWYm92Lwc8jyxwd4eYDEEtXJhF5SrFD/eN+e2d6V3Vk22qTlCZDOzKY3XEg5O5KAM0htYdSVcif47fpFJh6GFnvO0C2AiSoWLeqMXwiTijQK/nfc/WirqRK71UtGvQYTVjNn3Si8XETsFB3jwYuqV5T20cJ/13bZxxWCc6cU6M4=
  - secure: us9oCHkG8Ls9EogTh6h5ZbICKiwuKFX4IhuaayyGlPBgg5XLl3VY+FHEPMsxrSOaEhCvdXz3dijvfRp43HRa9bx9No1iL3ttIERwaXP7ERYKlRWUD6xh8p30XZ+NABo9xCFsIOYSJQbkvxaAFAbG11h4BX557s7bwNwJbVDBspc=
