dist: xenial
language: groovy
sudo: true
jdk:
- openjdk8
branches:
  only:
  - master
  - dev
  - /^feature\/.*$/
  - /^hotfix\/.*$/
node_js:
  - 12
addons:
  chrome: stable
  hosts: devt.ala.org.au

before_install:
- export TZ=Australia/Canberra
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env
before_script:
- nvm install 12.14.1
- nvm use 12.14.1
- node -v
- npm install
- sudo systemctl stop mongod
- sudo apt-get purge mongodb-org
- sudo apt autoremove
- sudo ls -la /var/log/mongodb
- sudo ls -al /var/lib/mongodb
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
- sudo apt-get update
- sudo apt-get install mongodb-org -y
- sudo systemctl start mongod
- sleep 15
- sudo ls -la /var/log/mongodb
- sudo ls -al /var/lib/mongodb
- sudo cat /var/log/mongodb/mongodb.log
- sudo systemctl status mongod
- sudo mongo -version


script:
- grails clean; grails refresh-dependencies --non-interactive; grails prod compile
- node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
- cd scripts
- chmod +x *.sh
- ./runFunctionalTests.sh chromeHeadless
- cd ..
- grails clean; grails refresh-dependencies --non-interactive && grails test-app -clover.on :unit --non-interactive --stacktrace && ala_travis_grails_build

env:
  global:
  - secure: cWYm92Lwc8jyxwd4eYDEEtXJhF5SrFD/eN+e2d6V3Vk22qTlCZDOzKY3XEg5O5KAM0htYdSVcif47fpFJh6GFnvO0C2AiSoWLeqMXwiTijQK/nfc/WirqRK71UtGvQYTVjNn3Si8XETsFB3jwYuqV5T20cJ/13bZxxWCc6cU6M4=
  - secure: us9oCHkG8Ls9EogTh6h5ZbICKiwuKFX4IhuaayyGlPBgg5XLl3VY+FHEPMsxrSOaEhCvdXz3dijvfRp43HRa9bx9No1iL3ttIERwaXP7ERYKlRWUD6xh8p30XZ+NABo9xCFsIOYSJQbkvxaAFAbG11h4BX557s7bwNwJbVDBspc=
