arch: amd64
os: linux
dist: xenial
language: groovy
jdk:
- openjdk8
branches:
  only:
  - master
  - dev
  - /^feature\/.*$/
  - /^hotfix\/.*$/
node_js:
  - 12
addons:
  chrome: stable
  hosts: devt.ala.org.au

services:
  - elasticsearch

before_install:
  - export TZ=Australia/Canberra
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches
  - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
  - chmod +x ala_common.sh
  - source ./ala_common.sh
  - ala_travis_grails_setup_env
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.3-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo sh -c 'echo ES_JAVA_OPTS=\"-Xmx512m -Xms512m\" >> /etc/default/elasticsearch'
  - sudo service elasticsearch restart

before_script:
- nvm install 12.14.1
- nvm use 12.14.1
- node -v
- npm install
- sudo systemctl stop mongod
- sudo apt-get purge mongodb-org
- sudo apt autoremove
- sudo rm -r /var/lib/mongodb/*
- sudo rm -r /var/log/mongodb/*
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
- sudo apt-get update
- sudo apt-get install mongodb-org -y
- sudo systemctl start mongod
- sleep 15
- sudo systemctl status mongod

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
  - ./gradlew test

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_retry ./gradlew publish'

env:
  global:
  - secure: cWYm92Lwc8jyxwd4eYDEEtXJhF5SrFD/eN+e2d6V3Vk22qTlCZDOzKY3XEg5O5KAM0htYdSVcif47fpFJh6GFnvO0C2AiSoWLeqMXwiTijQK/nfc/WirqRK71UtGvQYTVjNn3Si8XETsFB3jwYuqV5T20cJ/13bZxxWCc6cU6M4=
  - secure: us9oCHkG8Ls9EogTh6h5ZbICKiwuKFX4IhuaayyGlPBgg5XLl3VY+FHEPMsxrSOaEhCvdXz3dijvfRp43HRa9bx9No1iL3ttIERwaXP7ERYKlRWUD6xh8p30XZ+NABo9xCFsIOYSJQbkvxaAFAbG11h4BX557s7bwNwJbVDBspc=
