os: linux
dist: xenial
language: groovy
sudo: true
jdk:
- openjdk8
branches:
  only:
  - master
  - dev
  - /^hotfix\/.*$/
  - 'feature/grails4'
addons:
  chrome: stable

services:
  - mongodb

before_install:
  - export TZ=Australia/Canberra
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches

before_script:
  - nvm install 12.14.1
  - nvm use 12.14.1
  - node -v
  - npm install

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/wrapper/

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless
  - ./gradlew test

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew clean && travis_retry ./gradlew publish'

env:
  global:
  - secure: cWYm92Lwc8jyxwd4eYDEEtXJhF5SrFD/eN+e2d6V3Vk22qTlCZDOzKY3XEg5O5KAM0htYdSVcif47fpFJh6GFnvO0C2AiSoWLeqMXwiTijQK/nfc/WirqRK71UtGvQYTVjNn3Si8XETsFB3jwYuqV5T20cJ/13bZxxWCc6cU6M4=
  - secure: us9oCHkG8Ls9EogTh6h5ZbICKiwuKFX4IhuaayyGlPBgg5XLl3VY+FHEPMsxrSOaEhCvdXz3dijvfRp43HRa9bx9No1iL3ttIERwaXP7ERYKlRWUD6xh8p30XZ+NABo9xCFsIOYSJQbkvxaAFAbG11h4BX557s7bwNwJbVDBspc=
