meritVersion=5.0-SNAPSHOT
grailsVersion=7.2.4
assetPipelineVersion=5.0.34
geoToolsVersion=21.5
org.gradle.parallel=true
enableClover=false
enableJacoco=true
inplace=false
startWiremock=false
org.gradle.jvmargs=-Xmx2048M
seleniumVersion=3.141.59
seleniumSafariDriverVersion=3.14.0
snapshotCacheTime=1800
alaSecurityLibsVersion=8.0.0-SNAPSHOT
apachePoiVersion=5.2.3