name: MERIT build

on:
  push:
    branches:
      - githubactions
      - dev
      - master
      - feature/**
      - hotfix/**

env:
  TZ: Australia/Canberra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Install and start elasticsearch
        run: |
          curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-amd64.deb -o elasticsearch.deb
          sudo dpkg -i --force-confnew elasticsearch.deb
          sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          sudo sh -c 'echo ES_JAVA_OPTS=\"-Xmx1g -Xms1g\" >> /etc/default/elasticsearch'
          sudo service elasticsearch restart

      - name: Setup required MERIT folders
        run: |
          sudo mkdir -p /data/fieldcapture/cache
          sudo chmod o+xw /data
          sudo chmod o+xw /data/fieldcapture
          sudo chmod o+xw /data/fieldcapture/cache

      - name: Install and start mongodb
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.0'

      - name: Build and run clover coverage report with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: -PenableClover=true cloverGenerateReport
        env:
          GPR_USER: ${{env.GITHUB_ACTOR}}
          GPR_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install javascript packages using the gradle clientInstall plugin
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clientInstall

      - name: Run javascript unit tests
        run: node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless

      - name: Run MERIT functional tests
        run: ./src/main/scripts/runFunctionalTests.sh

      - name: Clean to remove clover instrumentation
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean

      - name: Publish the JAR to the repository
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
