name: MERIT build

on: [push]

env:
  TZ: Australia/Canberra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: npm install
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build and run clover coverage report with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: -PenableClover=true cloverGenerateReport

      - name: Install javascript packages using the gradle clientInstall plugin
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clientInstall

      - run: node_modules/karma/bin/karma start karma.conf.js --single-run --browsers ChromeHeadless

      - name: Install elasticsearch
        run: |
          curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-amd64.deb -o elasticsearch.deb
          sudo dpkg -i --force-confnew elasticsearch.deb
          sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          sudo sh -c 'echo ES_JAVA_OPTS=\"-Xmx256m -Xms256m\" >> /etc/default/elasticsearch'
          sudo service elasticsearch restart
          sudo mkdir -p /data/fieldcapture/cache
          sudo chmod o+xw /data
          sudo chmod o+xw /data/fieldcapture
          sudo chmod o+xw /data/fieldcapture/cache