---
appName:
  "fieldcapture"

server:
  session:
    timeout: 3600

environments:
    development:
      server:
        port: 8087
        contextPath: '/fieldcapture'



security:
  cas:
    appServerName: 'http://devt.ala.org.au:8087'
    casServerName: 'https://auth.ala.org.au'
    casServerUrlPrefix: 'https://auth.ala.org.au/cas'
    loginUrl: 'https://auth.ala.org.au/cas/login'
    logoutUrl: 'https://auth.ala.org.au/cas/logout'
    uriFilterPattern:
      - '/admin/*'
      - '/activityForm/*'
    authenticateOnlyIfLoggedInPattern:
    uriExclusionFilterPattern:
      - '/images/.*'
      - '/css/.*'
      - '/js/.*'
      - '/less/.*'
      - '/assets/.*'
      - '/activityForm/get.*'