---
appName:
  "fieldcapture"

server:
  servlet:
    session:
      timeout: 3600

environments:
    development:
      server:
        port: 8087
        contextPath: '/fieldcapture'
    test:
      server:
        contextPath: '/fieldcapture'
spring:
  devtools:
    livereload:
      enabled: true
