---
appName:
  "fieldcapture"

server:
  servlet:
    session:
      timeout: 3600

environments:
    development:
      server:
        port: 8087
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude:
        - '**/*.gsp'
        - '**/*.css'
        - '**/*.js'
