package au.org.ala.merit

enum EmailTemplate {
    DEFAULT_PLAN_SUBMITTED_EMAIL_TEMPLATE(SettingPageType.PLAN_SUBMITTED_EMAIL_SUBJECT_LINE, SettingPageType.PLAN_SUBMITTED_EMAIL),
    DEFAULT_PLAN_APPROVED_EMAIL_TEMPLATE(SettingPageType.PLAN_APPROVED_EMAIL_SUBJECT_LINE, SettingPageType.PLAN_APPROVED_EMAIL),
    DEFAULT_PLAN_RETURNED_EMAIL_TEMPLATE(SettingPageType.PLAN_REJECTED_EMAIL_SUBJECT_LINE, SettingPageType.PLAN_REJECTED_EMAIL),

    RLP_PLAN_SUBMITTED_EMAIL_TEMPLATE(SettingPageType.RLP_PLAN_SUBMITTED_EMAIL_SUBJECT_LINE, SettingPageType.RLP_PLAN_SUBMITTED_EMAIL),
    RLP_PLAN_APPROVED_EMAIL_TEMPLATE(SettingPageType.RLP_PLAN_APPROVED_EMAIL_SUBJECT_LINE, SettingPageType.RLP_PLAN_APPROVED_EMAIL),
    RLP_PLAN_RETURNED_EMAIL_TEMPLATE(SettingPageType.RLP_PLAN_REJECTED_EMAIL_SUBJECT_LINE, SettingPageType.RLP_PLAN_REJECTED_EMAIL),

    DEFAULT_REPORT_SUBMITTED_EMAIL_TEMPLATE(SettingPageType.REPORT_SUBMITTED_EMAIL_SUBJECT_LINE, SettingPageType.REPORT_SUBMITTED_EMAIL),
    DEFAULT_REPORT_APPROVED_EMAIL_TEMPLATE(SettingPageType.REPORT_APPROVED_EMAIL_SUBJECT_LINE, SettingPageType.REPORT_APPROVED_EMAIL),
    DEFAULT_REPORT_RETURNED_EMAIL_TEMPLATE(SettingPageType.REPORT_REJECTED_EMAIL_SUBJECT_LINE, SettingPageType.REPORT_REJECTED_EMAIL),

    RLP_REPORT_SUBMITTED_EMAIL_TEMPLATE(SettingPageType.RLP_REPORT_SUBMITTED_EMAIL_SUBJECT, SettingPageType.RLP_REPORT_SUBMITTED_EMAIL_BODY),
    RLP_REPORT_APPROVED_EMAIL_TEMPLATE(SettingPageType.RLP_REPORT_APPROVED_EMAIL_SUBJECT, SettingPageType.RLP_REPORT_APPROVED_EMAIL_BODY),
    RLP_REPORT_RETURNED_EMAIL_TEMPLATE(SettingPageType.RLP_REPORT_RETURNED_EMAIL_SUBJECT, SettingPageType.RLP_REPORT_RETURNED_EMAIL_BODY),

    RLP_CORE_SERVCIES_REPORT_SUBMITTED_EMAIL_TEMPLATE(SettingPageType.RLP_CORE_SERVICES_REPORT_SUBMITTED_EMAIL_SUBJECT, SettingPageType.RLP_CORE_SERVICES_REPORT_SUBMITTED_EMAIL_BODY),
    RLP_CORE_SERVICES_REPORT_APPROVED_EMAIL_TEMPLATE(SettingPageType.RLP_CORE_SERVICES_REPORT_APPROVED_EMAIL_SUBJECT, SettingPageType.RLP_CORE_SERVICES_REPORT_APPROVED_EMAIL_BODY),
    RLP_CORE_SERVICES_REPORT_RETURNED_EMAIL_TEMPLATE(SettingPageType.RLP_CORE_SERVICES_REPORT_RETURNED_EMAIL_SUBJECT, SettingPageType.RLP_CORE_SERVICES_REPORT_RETURNED_EMAIL_BODY)


    SettingPageType subjectSettingPage
    SettingPageType bodySettingPage

    EmailTemplate(SettingPageType subjectSettingPage, SettingPageType bodySettingPage) {
        this.subjectSettingPage = subjectSettingPage
        this.bodySettingPage = bodySettingPage
    }

}
